import * as THREE from 'three';
import { RoomEnvironment } from 'three/addons/environments/RoomEnvironment.js';

export function advanceConstructionProgress(current,target,dt,duration=36){
 const delta=target-current;
 return current+Math.sign(delta)*Math.min(Math.abs(delta)*(1-Math.exp(-dt*7)),dt/duration);
}

// A self-contained architectural model. No dependency on the original scene.
export class SiteModel {
 constructor(container,{paused=false,scrollDriven=false,onProgress=()=>{},duration=36,zoom=1}={}) {
  this.container=container;this.paused=paused;this.visible=true;this.stage=paused?2:0;this.time=0;this.last=0;this.pointer=new THREE.Vector2();this.disposed=false;this.onProgress=onProgress;
  this.scrollDriven=scrollDriven;this.scrollTarget=paused?1:0;this.progress=paused?1:0;this.sequenceStart=this.progress;this.sequenceTarget=1;this.sequenceElapsed=0;this.duration=duration;this.zoom=zoom;this.sequenceDuration=this.duration;this.sequencePlaying=!paused&&!scrollDriven;this.motionParts=[];this.panelFlights=[];this.scaffoldParts=[];this.mastParts=[];this.animationContext=null;
  this.scene=new THREE.Scene();this.scene.background=new THREE.Color('#e7ebe1');
  this.camera=new THREE.OrthographicCamera(-14,14,14,-14,.1,160);
  this.camera.position.set(25,22,29);this.target=new THREE.Vector3(0,5.2,0);this.camera.lookAt(this.target);
  this.renderer=new THREE.WebGLRenderer({antialias:true,alpha:false,powerPreference:'low-power'});
  this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.75));this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=THREE.PCFSoftShadowMap;
  this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.05;
  container.prepend(this.renderer.domElement);this.renderer.domElement.setAttribute('aria-hidden','true');
  const studio=new RoomEnvironment(),pmrem=new THREE.PMREMGenerator(this.renderer);this.environment=pmrem.fromScene(studio,.04);this.scene.environment=this.environment.texture;this.scene.environmentIntensity=.45;studio.dispose();pmrem.dispose();
  this.scene.add(new THREE.HemisphereLight('#fffff4','#737d6c',1.3));
  const sun=new THREE.DirectionalLight('#fff0d7',3.2);sun.position.set(-14,27,14);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-22;sun.shadow.camera.right=22;sun.shadow.camera.top=24;sun.shadow.camera.bottom=-20;sun.shadow.camera.near=1;sun.shadow.camera.far=75;sun.shadow.bias=-.0006;sun.shadow.normalBias=.035;sun.shadow.radius=4;this.scene.add(sun);
  const fill=new THREE.DirectionalLight('#e5efff',1.2);fill.position.set(15,12,-20);this.scene.add(fill);
  this.materials={};this.geometries=new Map();this.textures=[];
  const mat=(name,color,roughness=.75,metalness=0)=>this.materials[name]=new THREE.MeshStandardMaterial({color,roughness,metalness});
  mat('concrete','#bfc1b5');mat('concreteEdge','#b9c0b5');mat('steel','#59695b',.5,.45);mat('dark','#303c34');mat('rubber','#30332e');mat('amber','#cf823a',.46,.2);mat('amberLight','#e8a95b',.5,.15);mat('wood','#ba9b73');mat('white','#f4f1e7');mat('soil','#9a8060');mat('gravel','#c5baa2');mat('grass','#a0ab8d');mat('leaf','#6f8461');mat('leafLight','#8c9d75');mat('bark','#7b7054');mat('red','#b95c3d');mat('road','#a7aca1');this.materials.glass=new THREE.MeshPhysicalMaterial({color:'#8faeb0',roughness:.18,metalness:.12,clearcoat:.7,clearcoatRoughness:.14,transparent:true,opacity:.68,depthWrite:false,side:THREE.DoubleSide});mat('window','#304e4a',.2,.4);mat('vest','#e49b48');mat('skin','#c89e7d');
  // Fine mineral grain gives the concrete scale without using external textures.
  const tc=document.createElement('canvas');tc.width=128;tc.height=128;const ctx=tc.getContext('2d');const data=ctx.createImageData(128,128);let seed=4103;for(let i=0;i<data.data.length;i+=4){seed=(seed*16807)%2147483647;const v=174+(seed%58);data.data[i]=v;data.data[i+1]=v;data.data[i+2]=v-4;data.data[i+3]=255;}ctx.putImageData(data,0,0);const tex=new THREE.CanvasTexture(tc);tex.wrapS=tex.wrapT=THREE.RepeatWrapping;tex.repeat.set(3,3);tex.colorSpace=THREE.SRGBColorSpace;this.textures.push(tex);this.materials.concrete.map=tex;this.materials.concrete.bumpMap=tex;this.materials.concrete.bumpScale=.025;
  this.root=new THREE.Group();this.scene.add(this.root);this.foundation=new THREE.Group();this.structure=new THREE.Group();this.finished=new THREE.Group();this.equipment=new THREE.Group();this.root.add(this.foundation,this.structure,this.finished,this.equipment);
  this.buildGround();this.buildBuilding();this.buildCrane();this.buildEquipment();this.buildDetails();
  const floor=new THREE.Mesh(new THREE.PlaneGeometry(200,200),new THREE.ShadowMaterial({color:'#364732',opacity:.14}));floor.rotation.x=-Math.PI/2;floor.position.y=-.62;floor.receiveShadow=true;this.scene.add(floor);
  this.resize=()=>{const w=container.clientWidth,h=container.clientHeight;if(!w||!h)return;this.renderer.setSize(w,h);const aspect=w/h;const cinematic=window.innerWidth>760;const span=Math.max(12.1,(cinematic?23:15.3)/aspect);this.camera.left=-span*aspect*(cinematic?1.36:1);this.camera.right=span*aspect*(cinematic?.64:1);this.camera.top=span;this.camera.bottom=-span;this.camera.zoom=this.zoom;this.camera.updateProjectionMatrix();this.render();};
  this.observer=new ResizeObserver(this.resize);this.observer.observe(container);
  this.intersection=new IntersectionObserver(([entry])=>{this.visible=entry.isIntersecting;this.last=0;},{rootMargin:'100px'});this.intersection.observe(container);
  this.onPointer=e=>{if(this.paused||e.pointerType==='touch')return;const r=container.getBoundingClientRect();this.pointer.set((e.clientX-r.left)/r.width-.5,(e.clientY-r.top)/r.height-.5);};
  this.onLeave=()=>this.pointer.set(0,0);container.addEventListener('pointermove',this.onPointer);container.addEventListener('pointerleave',this.onLeave);
  this.onVisibility=()=>{this.last=0;};document.addEventListener('visibilitychange',this.onVisibility);
  this.onContextLost=e=>{e.preventDefault();this.paused=true;container.querySelector('.scene-fallback').hidden=false;this.renderer.domElement.style.visibility='hidden';};this.renderer.domElement.addEventListener('webglcontextlost',this.onContextLost);
  this.onPageHide=()=>this.dispose();window.addEventListener('pagehide',this.onPageHide,{once:true});
  this.applyConstruction(this.progress);this.resize();this.reportProgress();this.tick=this.tick.bind(this);this.frame=requestAnimationFrame(this.tick);
 }
 box(parent,w,h,d,x,y,z,material,rotation=0){let key=`b:${w}:${h}:${d}`;let geo=this.geometries.get(key);if(!geo){geo=new THREE.BoxGeometry(w,h,d);this.geometries.set(key,geo);}const mesh=new THREE.Mesh(geo,this.materials[material]);mesh.position.set(x,y,z);mesh.rotation.y=rotation;mesh.castShadow=true;mesh.receiveShadow=true;parent.add(mesh);if(this.animationContext?.kind==='box')this.growBox(mesh,this.animationContext.axis,this.animationContext.extent,this.animationContext.start,this.animationContext.end,this.animationContext.direction??1,this.animationContext.collection);return mesh;}
 cylinder(parent,r,h,x,y,z,material,segments=12){const key=`c:${r}:${h}:${segments}`;let geo=this.geometries.get(key);if(!geo){geo=new THREE.CylinderGeometry(r,r,h,segments);this.geometries.set(key,geo);}const m=new THREE.Mesh(geo,this.materials[material]);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
 beam(parent,a,b,r,material){const av=new THREE.Vector3(...a),bv=new THREE.Vector3(...b),dir=bv.clone().sub(av);const m=this.cylinder(parent,r,dir.length(),0,0,0,material,6);m.position.copy(av.clone().add(bv).multiplyScalar(.5));m.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),dir.normalize());if(this.animationContext?.kind==='beam')this.growBeam(m,av,bv,this.animationContext.start,this.animationContext.end,this.animationContext.collection);return m;}
 growBox(mesh,axis,extent,start,end,direction=1,collection=null){const target=mesh.position.clone(),anchor=target[axis]-direction*extent/2;mesh.scale[axis]=.001;mesh.position[axis]=anchor+direction*extent*.001/2;const part={type:'box',mesh,axis,extent,direction,anchor,start,end,target};this.motionParts.push(part);if(collection)collection.push(part);}
 growBeam(mesh,a,b,start,end,collection=null){const from=a.clone(),to=b.clone();mesh.scale.y=.001;mesh.position.copy(from.clone().add(to).multiplyScalar(.0005));const part={type:'beam',mesh,from,to,start,end,target:from.clone().add(to).multiplyScalar(.5)};this.motionParts.push(part);if(collection)collection.push(part);}
 queueFlight(group,source,start,end,sourceTilt=Math.PI/2,sourceYaw=0){const target=group.position.clone(),rotation=group.quaternion.clone(),fromRotation=new THREE.Quaternion().setFromEuler(new THREE.Euler(sourceTilt,sourceYaw,0)),sourceOffset=new THREE.Vector3(...source);group.visible=false;group.quaternion.copy(fromRotation);this.panelFlights.push({group,sourceOffset,fromRotation,target,rotation,start,end});}
 buildGround(){
  this.box(this.root,22,.65,17,0,-.25,0,'concreteEdge');this.box(this.root,21.7,.12,16.7,0,.12,0,'gravel');
  this.box(this.root,22,.04,3.1,0,.22,6.85,'road');this.box(this.root,22,.12,.2,0,.27,5.24,'concreteEdge');
  for(let x=-10;x<11;x+=2.5)this.box(this.root,1.3,.012,.055,x,.25,7,'white');
  this.excavation=new THREE.Group();this.footings=new THREE.Group();this.rebar=new THREE.Group();this.foundation.add(this.excavation,this.footings,this.rebar);
  this.box(this.excavation,10,.38,8,-1,-.2,-1.1,'soil');
  let footingIndex=0,rebarIndex=0;
  for(let x=-5.2;x<=3.3;x+=2.8)for(let z=-4.4;z<=2.5;z+=2.3){this.animationContext={kind:'box',axis:'y',extent:.5,start:.09+footingIndex*.008,end:.15+footingIndex*.008};this.box(this.footings,1.35,.5,1.35,x,.3,z,'concrete');footingIndex++;for(let j=0;j<3;j++){this.animationContext={kind:'beam',start:.15+rebarIndex*.002,end:.168+rebarIndex*.002};this.beam(this.rebar,[x-.35+j*.35,.56,z-.4],[x-.35+j*.35,1.3,z-.4],.023,'steel');rebarIndex++;}}
  // Reinforcement grid over the foundation footprint.
  for(let x=-5.5;x<=3.6;x+=.5){this.animationContext={kind:'beam',start:.18+rebarIndex*.0008,end:.205+rebarIndex*.0008};this.beam(this.rebar,[x,.48,-4.8],[x,.48,2.7],.018,'steel');rebarIndex++;}for(let z=-4.8;z<=2.7;z+=.5){this.animationContext={kind:'beam',start:.18+rebarIndex*.0008,end:.205+rebarIndex*.0008};this.beam(this.rebar,[-5.5,.49,z],[3.6,.49,z],.018,'steel');rebarIndex++;}this.animationContext=null;
  for(let x=-10.3;x<=10.3;x+=1.35){if(x>3&&x<7)continue;this.fence(x,4.85,0);}
  for(let z=-7.5;z<4.5;z+=1.35)this.fence(-10.2,z,Math.PI/2);
  this.box(this.root,4.1,.15,1.7,7.2,.27,-6.7,'grass');
 }
 fence(x,z,rot){const g=new THREE.Group();g.position.set(x,0,z);g.rotation.y=rot;this.root.add(g);this.box(g,1.3,.7,.05,0,.9,0,'steel');this.box(g,.055,1.2,.055,-.63,.78,0,'steel');this.box(g,.055,1.2,.055,.63,.78,0,'steel');for(let i=-.5;i<.6;i+=.22)this.box(g,.025,.8,.04,i,.91,.035,'concreteEdge');this.box(g,.34,.1,.28,-.63,.3,0,'concrete');}
 buildBuilding(){
  const g=this.structure;this.temporary=new THREE.Group();g.add(this.temporary);this.frameLevels=[];this.stairLevels=[];
  const slabStarts=[.28,.44,.60];
  for(let level=0;level<3;level++){
   const deck=new THREE.Group();g.add(deck);this.frameLevels.push(deck);const y=.65+level*2.45,at=slabStarts[level],columnAt=at+.08;
   // Each deck is poured across its span only after the level below has reached full height.
   this.animationContext={kind:'box',axis:'z',extent:7.5,start:at,end:at+.08};this.box(deck,10,.26,7.5,-1,y,-1.2,'concrete');
   this.animationContext={kind:'box',axis:'z',extent:7.58,start:at+.012,end:at+.092};this.box(deck,10.08,.085,7.58,-1,y+.14,-1.2,'concreteEdge');
   for(const x of [-5.7,-1,3.7])for(const z of [-4.6,-1.2,2.2]){this.animationContext={kind:'box',axis:'y',extent:.13,start:columnAt,end:columnAt+.008};this.box(deck,.46,.13,.46,x,y+.22,z,'steel');this.animationContext={kind:'box',axis:'y',extent:2.25,start:columnAt+.008,end:columnAt+.073};this.box(deck,.3,2.25,.3,x,y+1.25,z,'concreteEdge');}
   for(const x of [-5.7,-1,3.7]){this.animationContext={kind:'box',axis:'z',extent:7.1,start:columnAt+.01,end:columnAt+.07};this.box(deck,.17,.26,7.1,x,y-.15,-1.2,'steel');}
   this.animationContext=null;
   const stair=new THREE.Group();g.add(stair);this.stairLevels.push(stair);for(let s=0;s<12;s++){const t=at+.15+s*.0015;this.animationContext={kind:'box',axis:'y',extent:.16,start:t,end:t+.014};this.box(stair,1.05,.16,.25,-4.9,.9+level*2.45+s*.18,-.7+s*.2,'concreteEdge');}
  }
  this.animationContext=null;
  // The lift core is cast floor by floor with its door reveal following each pour.
  this.core=new THREE.Group();g.add(this.core);
  for(let level=0;level<3;level++){const base=.65+level*2.45,at=slabStarts[level]+.08,y=base+1.225;this.animationContext={kind:'box',axis:'y',extent:2.45,start:at,end:at+.065};this.box(this.core,1.65,2.45,2,-3.8,y,-3.5,'concrete');this.animationContext={kind:'box',axis:'y',extent:1.65,start:at+.05,end:at+.07};this.box(this.core,.75,1.65,.04,-3.8,y,-2.48,'dark');this.animationContext={kind:'box',axis:'y',extent:1.75,start:at+.05,end:at+.07};this.box(this.core,.08,1.75,.08,-4.22,y,-2.43,'steel');}
  let bay=0;const scaffoldStarts=[.36,.52,.68,.79];for(let x=-6.5;x<=4.7;x+=1.6){for(let floor=0;floor<4;floor++){const y=.3+floor*2.1,at=scaffoldStarts[floor]+bay*.0015;for(const z of [2.95,3.72]){this.animationContext={kind:'beam',start:at,end:at+.035,collection:this.scaffoldParts};this.beam(this.temporary,[x,y,z],[x,y+2.1,z],.033,'steel');}for(const z of [2.95,3.72]){this.animationContext={kind:'beam',start:at+.015,end:at+.05,collection:this.scaffoldParts};this.beam(this.temporary,[x,y+2.1,z],[x+1.6,y+2.1,z],.035,'steel');}if(x<4){for(const z of [2.95,3.72]){this.animationContext={kind:'beam',start:at+.018,end:at+.055,collection:this.scaffoldParts};this.beam(this.temporary,[x,y,z],[x+1.6,y+2.1,z],.022,'steel');}this.animationContext={kind:'box',axis:'x',extent:1.55,start:at+.022,end:at+.06,collection:this.scaffoldParts};this.box(this.temporary,1.55,.065,.72,x+.8,y+2.03,3.34,'wood');}}bay++;}
  this.animationContext=null;
  this.roof=new THREE.Group();this.finished.add(this.roof);this.animationContext={kind:'box',axis:'z',extent:7.8,start:.76,end:.84};this.box(this.roof,10.3,.3,7.8,-1,8.13,-1.2,'concreteEdge');let roofIndex=0;
  for(let x=-2.5;x<3;x+=1.2)for(let z=-3.7;z<1.5;z+=1.5){const at=.84+roofIndex*.0044;this.animationContext={kind:'box',axis:'z',extent:1.3,start:at,end:at+.02};const panel=this.box(this.roof,1.05,.08,1.3,x,8.4,z,'window');panel.rotation.x=-.15;this.animationContext={kind:'box',axis:'z',extent:1.3,start:at+.006,end:at+.026};this.box(this.roof,.025,.025,1.3,x,8.49,z,'steel');roofIndex++;}this.animationContext=null;
  this.facadeLevels=[];let panelIndex=0;
  const installPanel=(target,side,level)=>{const panel=new THREE.Group();this.finished.add(panel);panel.position.copy(target);if(side==='front'){this.box(panel,1.9,2.04,.065,0,0,0,'glass');for(const x of [-.96,.96])this.box(panel,.045,2.15,.105,x,0,0,'steel');for(const y of [-1.04,0,1.04])this.box(panel,1.9,.045,.105,0,y,0,'steel');}else{this.box(panel,.065,2.04,2.42,0,0,0,'glass');for(const z of [-1.21,1.21])this.box(panel,.105,2.15,.045,0,0,z,'steel');for(const y of [-1.04,0,1.04])this.box(panel,.105,.045,2.42,0,y,0,'steel');}const rigging=new THREE.Group();panel.add(rigging);if(side==='front'){this.beam(rigging,[-.68,1.08,0],[0,1.4,0],.014,'steel');this.beam(rigging,[.68,1.08,0],[0,1.4,0],.014,'steel');this.box(rigging,1.38,.055,.07,0,1.4,0,'steel');}else{this.beam(rigging,[0,1.08,-.68],[0,1.4,0],.014,'steel');this.beam(rigging,[0,1.08,.68],[0,1.4,0],.014,'steel');this.box(rigging,.07,.055,1.38,0,1.4,0,'steel');}const n=panelIndex++,source=[.5,1.8,(n-11.5)*.072],start=.50+n*.018;this.queueFlight(panel,source,start,start+.014,0,side==='side'?Math.PI/2:0);this.panelFlights[this.panelFlights.length-1].rigging=rigging;};
  for(let level=0;level<3;level++){for(const x of [-5.1,-3.05,-1,1.05,3.1])installPanel(new THREE.Vector3(x,1.98+level*2.45,2.33),'front',level);for(const z of [-4.0,-1.3,1.4])installPanel(new THREE.Vector3(3.86,1.98+level*2.45,z),'side',level);}
 } buildCrane(){
  this.crane=new THREE.Group();this.crane.position.set(5.8,.35,-2.9);this.equipment.add(this.crane);const g=this.crane;this.box(g,2,.4,2,0,.1,0,'concrete');this.craneMastSections=[];
  let sectionIndex=0;for(let y=.3;y<13.6;y+=1.15){const section=new THREE.Group();g.add(section);this.craneMastSections.push(section);const start=.2+sectionIndex*.014,end=start+.065;for(const x of [-.43,.43])for(const z of [-.43,.43]){this.animationContext={kind:'beam',start,end};this.beam(section,[x,y,z],[x,y+1.15,z],.055,'amber');}for(const z of [-.43,.43]){this.animationContext={kind:'beam',start:start+.015,end:end+.015};this.beam(section,[-.43,y,z],[.43,y+1.15,z],.037,'amber');this.beam(section,[.43,y,z],[-.43,y+1.15,z],.037,'amber');this.beam(section,[-.43,y,z],[.43,y,z],.045,'amber');}for(const x of [-.43,.43]){this.animationContext={kind:'beam',start:start+.02,end:end+.02};this.beam(section,[x,y,-.43],[x,y+1.15,.43],.035,'amber');}sectionIndex++;}
  this.animationContext=null;this.craneHead=new THREE.Group();this.craneHead.position.y=-13.65;g.add(this.craneHead);this.cylinder(this.craneHead,.65,.32,0,13.65,0,'steel');this.jib=new THREE.Group();this.jib.position.y=13.9;this.jib.rotation.y=-Math.PI+.45;this.craneHead.add(this.jib);const j=this.jib;
  let jibIndex=0;for(let x=-3.4;x<12;x+=.8){for(const z of [-.35,.35]){const start=.37+jibIndex*.00045;this.animationContext={kind:'beam',start,end:start+.035};this.beam(j,[x,0,z],[x+.8,0,z],.045,'amber');this.beam(j,[x,0,z],[x+.8,.7,0],.033,'amber');this.beam(j,[x,.7,0],[x+.8,0,z],.033,'amber');this.animationContext={kind:'beam',start:start+.01,end:start+.045};this.beam(j,[x,.7,0],[x+.8,.7,0],.05,'amber');jibIndex++;}}
  this.animationContext={kind:'beam',start:.40,end:.46};this.beam(j,[0,.2,0],[0,2.1,0],.07,'amber');this.beam(j,[0,2.1,0],[12,.6,0],.023,'steel');this.beam(j,[0,2.1,0],[-3.4,.6,0],.023,'steel');
  for(let x=-3.2;x<-1.5;x+=.45){this.animationContext={kind:'box',axis:'y',extent:1.1,start:.41,end:.47};this.box(j,.38,1.1,1.05,x,-.25,0,'concrete');}this.animationContext={kind:'box',axis:'y',extent:1.1,start:.43,end:.49};this.box(j,.9,1.1,.95,.55,-.65,.3,'amberLight');this.box(j,.65,.66,.04,.6,-.57,.8,'window');this.box(j,.04,.66,.65,1.02,-.57,.25,'window');this.animationContext=null;
  // The trolley physically carries the hoist along the jib rails as each panel is lifted.
  this.trolley=new THREE.Group();this.trolley.position.set(2.5,0,0);this.trolley.visible=false;j.add(this.trolley);this.box(this.trolley,.78,.22,.92,0,-.1,0,'amber');this.box(this.trolley,.48,.3,.54,0,-.32,0,'steel');for(const x of [-.27,.27])for(const z of [-.42,.42]){const wheel=this.cylinder(this.trolley,.13,.12,x,.08,z,'dark');wheel.rotation.x=Math.PI/2;const pin=this.cylinder(this.trolley,.055,.13,x,.08,z,'amberLight');pin.rotation.x=Math.PI/2;}
  this.hook=new THREE.Group();this.trolley.add(this.hook);this.hoistCable=this.beam(this.hook,[0,0,0],[0,-6.4,0],.026,'dark');this.hookHardware=new THREE.Group();this.hook.add(this.hookHardware);this.hookHardware.position.y=-6.4;this.box(this.hookHardware,.28,.35,.23,0,-.15,0,'amber');this.beam(this.hookHardware,[0,-.3,0],[0,-.6,0],.045,'steel');this.beam(this.hookHardware,[0,-.6,0],[.18,-.6,0],.045,'steel');
 } excavator(x,z){const g=new THREE.Group();g.position.set(x,.4,z);g.rotation.y=-.5;this.equipment.add(g);this.excavatorGroup=g;
  for(const zz of [-.53,.53]){this.box(g,2.25,.42,.37,0,.2,zz,'rubber');for(let xx=-.9;xx<1;xx+=.29){const w=this.cylinder(g,.22,.4,xx,.23,zz,'steel');w.rotation.x=Math.PI/2;}for(let xx=-1;xx<1.2;xx+=.18)this.box(g,.08,.035,.4,xx,.44,zz,'dark');}
  this.cylinder(g,.58,.2,0,.58,0,'steel');this.box(g,1.1,.65,1.1,-.5,.98,0,'amber');this.box(g,.68,.94,.78,.3,1.25,-.22,'amberLight');this.box(g,.5,.6,.025,.31,1.36,.18,'window');this.box(g,.03,.6,.6,.66,1.36,-.22,'window');this.box(g,.8,.09,.9,.3,1.78,-.22,'dark');
  this.excavatorUpper=new THREE.Group();this.excavatorUpper.position.set(.4,1,0);g.add(this.excavatorUpper);this.beam(this.excavatorUpper,[0,0,0],[.95,1.8,0],.17,'amber');this.beam(this.excavatorUpper,[.18,.35,.19],[.7,1.47,.19],.075,'amberLight');this.beam(this.excavatorUpper,[.34,.52,.23],[.69,1.38,.23],.03,'steel');
  this.excavatorStick=new THREE.Group();this.excavatorStick.position.set(.95,1.8,0);this.excavatorUpper.add(this.excavatorStick);this.beam(this.excavatorStick,[0,0,0],[1.35,-1.7,0],.13,'amber');this.beam(this.excavatorStick,[.14,-.18,.16],[1.1,-1.43,.16],.055,'amberLight');this.beam(this.excavatorStick,[.35,-.35,.2],[1.08,-1.34,.2],.026,'steel');
  this.excavatorBucket=new THREE.Group();this.excavatorBucket.position.set(1.35,-1.7,0);this.excavatorStick.add(this.excavatorBucket);this.box(this.excavatorBucket,.65,.48,.65,0,0,0,'dark',-.4);for(let i=0;i<4;i++)this.box(this.excavatorBucket,.34,.08,.07,.3,-.22,-.24+i*.16,'steel');
 }
 buildEquipment(){this.excavator(-7.8,.6);
  // Flatbed truck with windows, wheel wells, bed and stacked materials.
  const truck=new THREE.Group();truck.position.set(8.8,.3,6.8);this.root.add(truck);this.truck=truck;
  this.box(truck,3.5,.25,1.8,0,.55,0,'dark');this.box(truck,1.15,1.25,1.35,-1.25,1.25,0,'white');this.box(truck,.03,.65,1.05,-1.84,1.4,0,'window');this.box(truck,.73,.64,.03,-1.23,1.4,.69,'window');this.box(truck,.73,.64,.03,-1.23,1.4,-.69,'window');this.box(truck,2.1,.16,1.8,.5,.75,0,'wood');
  for(const x of [-1.15,1.13])for(const z of [-.92,.92]){const w=this.cylinder(truck,.36,.2,x,.4,z,'rubber');w.rotation.x=Math.PI/2;const hub=this.cylinder(truck,.16,.21,x,.4,z,'concreteEdge');hub.rotation.x=Math.PI/2;}
  // A-frame glazing rack carries upright cassettes on the flatbed.
  for(const x of [-.45,1.3]){this.beam(truck,[x,.78,-.88],[x,2.55,0],.045,'steel');this.beam(truck,[x,.78,.88],[x,2.55,0],.045,'steel');this.beam(truck,[x,2.52,-.08],[x,2.52,.08],.045,'amber');}
  // Site office with ribbed cladding, entrance and rooftop ventilation.
  this.box(this.root,3.2,1.8,2.1,7.7,1.13,-6.4,'white');this.box(this.root,3.36,.15,2.25,7.7,2.09,-6.4,'steel');for(let x=6.2;x<9.3;x+=.19)this.box(this.root,.027,1.7,.035,x,1.14,-5.33,'concrete');this.box(this.root,.65,1.4,.04,6.65,.98,-5.28,'steel');for(const x of [7.65,8.65]){this.box(this.root,.75,.75,.045,x,1.4,-5.28,'window');this.box(this.root,.8,.05,.12,x,1,-5.25,'white');}this.box(this.root,.8,.35,.7,8.5,2.33,-6.3,'concrete');
 }
 worker(x,y,z,rot=0){const g=new THREE.Group();g.position.set(x,y,z);g.rotation.y=rot;this.root.add(g);this.box(g,.25,.37,.19,0,.56,0,'vest');this.cylinder(g,.105,.18,0,.88,0,'skin');this.cylinder(g,.14,.08,0,.99,0,'white');for(const s of [-1,1]){this.box(g,.085,.35,.1,s*.08,.21,0,'dark');this.beam(g,[s*.18,.7,0],[s*.21,.39,.04],.045,'vest');}this.box(g,.27,.025,.02,0,.58,.11,'white');return g;}
 tree(x,z,size=1){const g=new THREE.Group();g.position.set(x,.35,z);g.scale.setScalar(size);this.root.add(g);this.cylinder(g,.12,1.8,0,.9,0,'bark');const geo=new THREE.IcosahedronGeometry(.8,2);for(let i=0;i<5;i++){const m=new THREE.Mesh(geo,this.materials[i%2?'leaf':'leafLight']);m.position.set(Math.sin(i*2.4)*.48,1.7+(i%3)*.35,Math.cos(i*2.4)*.4);m.scale.set(1,1.2,1);m.castShadow=true;g.add(m);}}
 buildDetails(){
  for(let i=0;i<5;i++)this.tree(-9.3+i*4.3,-7.25,.7+(i%3)*.12);
  this.worker(8.2,.3,1.5);this.worker(-4.7,.3,4.35);this.worker(2.3,.3,.8,.7);
  // Stacked pipes, timber pallets, service cabinet and concrete barriers.
  for(let i=0;i<5;i++){const pipe=this.cylinder(this.root,.12,2.5,-7.8+i*.25,.6,-4.8,'steel');pipe.rotation.x=Math.PI/2;}
  for(let y=0;y<3;y++)for(let x=0;x<4;x++)this.box(this.root,.2,.14,1.9,7+x*.25,.43+y*.15,2.7,'wood');
  this.box(this.root,.9,1.1,.65,-8.8,.84,-2.8,'steel');this.box(this.root,.65,.75,.03,-8.8,.86,-2.46,'white');
  for(let x=4;x<8;x+=1.6){this.box(this.root,1.25,.52,.37,x,.48,4.8,'concreteEdge');this.box(this.root,.3,.22,.025,x,.56,5,'red');}
  for(const x of [-8.5,8.8]){this.beam(this.root,[x,.3,5.6],[x,3.5,5.6],.035,'steel');this.box(this.root,.55,.07,.2,x+.17,3.5,5.6,'steel');}
  this.box(this.root,1.6,.9,.08,-8.3,1.8,4.83,'white');this.box(this.root,.09,.8,.085,-8.9,1.8,4.88,'amber');
 }
 applyConstruction(progress){
  const p=THREE.MathUtils.clamp(progress,0,1),smooth=(a,b)=>THREE.MathUtils.smoothstep(p,a,b);
  this.target.y=2.8+2.4*smooth(.15,.55);this.camera.lookAt(this.target);
  this.excavation.position.y=.25-.65*smooth(.01,.15,p);
  for(const part of this.motionParts){const t=smooth(part.start,part.end);part.mesh.visible=t>.005;if(part.type==='box'){part.mesh.scale[part.axis]=t;part.mesh.position[part.axis]=part.anchor+part.direction*part.extent*t/2;}else{part.mesh.scale.y=t;part.mesh.position.copy(part.from.clone().lerp(part.to,t/2));}part.mesh.castShadow=t>.16;part.mesh.receiveShadow=t>.25;}
  this.finished.visible=true;
  this.core.visible=true;
  this.crane.visible=true;this.craneHead.position.y=-13.65*(1-smooth(.37,.49,p));this.trolley.visible=smooth(.46,.49,p)>.005;if(p<.48){this.jib.rotation.y=-Math.PI+.45;this.trolley.position.set(2.5,0,0);this.hook.position.set(0,0,0);this.hoistCable.scale.y=1;this.hoistCable.position.y=-3.2;this.hookHardware.position.y=-6.4;}
  for(const flight of this.panelFlights){const from=this.truck.position.clone().add(flight.sourceOffset);if(p<flight.start){flight.group.visible=true;flight.rigging.visible=false;flight.group.position.copy(from);flight.group.quaternion.copy(flight.fromRotation);continue;}const t=smooth(flight.start,flight.end),control=from.clone().lerp(flight.target,.5);control.y=Math.max(from.y,flight.target.y)+3.1;const a=from.clone().lerp(control,t),b=control.clone().lerp(flight.target,t);flight.group.visible=t>.005;flight.rigging.visible=t>.015&&t<.995;flight.group.position.copy(a.lerp(b,t));flight.group.quaternion.slerpQuaternions(flight.fromRotation,flight.rotation,t);}
  this.scaffoldParts.forEach((part,i)=>{const height=part.target.y,departAt=.93+Math.max(0,7.8-height)*.0018,t=smooth(departAt,departAt+.035,p);if(t>0){const exit=part.target.clone();exit.z+=11;exit.y=.35;const arc=part.target.clone().lerp(exit,t);arc.y+=Math.sin(Math.PI*t)*1.1;part.mesh.position.copy(arc);if(t>=.999)part.mesh.visible=false;}});
  const parkExcavator=smooth(.12,.29);this.excavatorGroup.position.x=-7.8-.6*parkExcavator;this.excavatorGroup.position.z=.6-2*parkExcavator;this.excavatorGroup.rotation.y=-.5+1.1*parkExcavator;
  const digProgress=THREE.MathUtils.clamp((p-.02)/.13,0,1),digPhase=digProgress*2%1,digStroke=THREE.MathUtils.smoothstep(digPhase,0,.34)*(1-THREE.MathUtils.smoothstep(digPhase,.54,.94));this.excavatorUpper.rotation.z=-.5*digStroke;this.excavatorStick.rotation.z=-.8*digStroke;this.excavatorBucket.rotation.z=.65*digStroke;
  const arrive=smooth(.27,.42,p),depart=smooth(.94,.995,p);this.truck.position.x=9.2-arrive*3.6+depart*3.2;this.truck.visible=true;
  if(p>=.48){this.root.updateMatrixWorld(true);const flight=this.panelFlights.find(item=>p>=item.start&&p<item.end),next=this.panelFlights.find(item=>p<item.start),previous=[...this.panelFlights].reverse().find(item=>p>=item.end);let liftPoint;const rackPoint=item=>this.root.localToWorld(this.truck.position.clone().add(item.sourceOffset).add(new THREE.Vector3(0,1.4,0)));if(flight)liftPoint=flight.group.localToWorld(new THREE.Vector3(0,1.4,0));else if(previous&&next){const placed=previous.group.localToWorld(new THREE.Vector3(0,1.4,0)),rack=rackPoint(next);liftPoint=placed.lerp(rack,smooth(previous.end,next.start));}else if(next)liftPoint=rackPoint(next);else if(previous){const placed=previous.group.localToWorld(new THREE.Vector3(0,1.4,0)),park=this.root.localToWorld(new THREE.Vector3(-1,12.6,-1.2));liftPoint=placed.lerp(park,smooth(previous.end,Math.min(previous.end+.025,1),p));}else liftPoint=this.root.localToWorld(new THREE.Vector3(-1,12.6,-1.2));const base=this.crane.localToWorld(new THREE.Vector3(0,0,0)),dx=liftPoint.x-base.x,dz=liftPoint.z-base.z;this.jib.rotation.y=Math.atan2(-dz,dx);this.root.updateMatrixWorld(true);const localLift=this.jib.worldToLocal(liftPoint.clone()),rope=Math.max(.7,-localLift.y-.6);this.trolley.position.set(localLift.x,0,0);this.hook.position.set(0,0,localLift.z);this.hoistCable.scale.y=rope/6.4;this.hoistCable.position.y=-rope/2;this.hookHardware.position.y=-rope;}
 } reportProgress(){const p=this.progress,stage=p<.28?0:p<.95?1:2;if(stage!==this.stage){this.stage=stage;this.render();}this.onProgress(p,stage);}
 setStage(stage){const targets=[.275,.58,1],target=targets[stage]??1;this.sequenceStart=this.progress;this.sequenceTarget=target;this.sequenceElapsed=0;this.sequenceDuration=Math.max(1.5,Math.abs(target-this.progress)*this.duration);this.sequencePlaying=!this.paused;if(this.paused){this.progress=target;this.applyConstruction(target);this.reportProgress();this.render();}}
 setScrollProgress(value){this.scrollTarget=THREE.MathUtils.clamp(value,0,1);}
 setPaused(value){this.paused=value;this.pointer.set(0,0);if(!value&&!this.scrollDriven&&this.progress<1){this.sequenceStart=this.progress;this.sequenceTarget=1;this.sequenceElapsed=0;this.sequenceDuration=Math.max(2,(1-this.progress)*this.duration);this.sequencePlaying=true;}if(value)this.sequencePlaying=false;this.render();}
 render(){if(!this.disposed)this.renderer.render(this.scene,this.camera);}
 tick(now){if(this.disposed)return;this.frame=requestAnimationFrame(this.tick);if(!this.visible||document.hidden){this.last=0;return;}if(now-this.last<33)return;const dt=this.last?Math.min((now-this.last)/1000,.1):0;this.last=now;if(!this.paused){let dirty=false;if(this.scrollDriven&&Math.abs(this.scrollTarget-this.progress)>.00005){this.progress=advanceConstructionProgress(this.progress,this.scrollTarget,dt,this.duration);this.applyConstruction(this.progress);this.reportProgress();dirty=true;}if(this.sequencePlaying){this.sequenceElapsed+=dt;const t=THREE.MathUtils.clamp(this.sequenceElapsed/this.sequenceDuration,0,1),eased=t*t*(3-2*t);this.progress=THREE.MathUtils.lerp(this.sequenceStart,this.sequenceTarget,eased);this.applyConstruction(this.progress);this.reportProgress();this.sequencePlaying=t<1;dirty=true;}const rotation=this.pointer.x*.12;if(Math.abs(this.root.rotation.y-rotation)>.0001){this.root.rotation.y=THREE.MathUtils.lerp(this.root.rotation.y,rotation,.035);dirty=true;}if(dirty)this.render();}}
 dispose(){if(this.disposed)return;this.disposed=true;cancelAnimationFrame(this.frame);this.observer.disconnect();this.intersection.disconnect();this.container.removeEventListener('pointermove',this.onPointer);this.container.removeEventListener('pointerleave',this.onLeave);document.removeEventListener('visibilitychange',this.onVisibility);window.removeEventListener('pagehide',this.onPageHide);const geometries=new Set(),materials=new Set();this.scene.traverse(o=>{if(o.geometry)geometries.add(o.geometry);if(o.material)materials.add(o.material);});geometries.forEach(g=>g.dispose());materials.forEach(m=>m.dispose());this.textures.forEach(t=>t.dispose());this.environment?.dispose();this.renderer.dispose();}
}
