import './site/site.css';
import './site/constructionStory.css';
import { createIcons, ArrowUpRight, ArrowRight, ArrowLeft, Check, ChevronRight, Users, ClipboardList, ShieldCheck, Wrench, Truck, ChartNoAxesCombined, BriefcaseBusiness, ReceiptText, HardHat, UserCheck, Hammer, Contact, Info, Link, Download, ScanLine, Radio, FileCheck, Eye, Clock, Paperclip, Menu, X, Settings2, Pause, Play, Plus, Minus, CheckCheck, MapPin, Circle, Mail, ChevronDown, Building2, Layers3 } from 'lucide';
import { homePage, bindHome, platformPage, bindPlatform, rolesPage, bindRoles, aboutPage, legalPage, notFound, signInPage } from './site/pages.js';
import { pricingPage, bindPricing } from './site/pricing.js';
import { contactPage, bindContact } from './site/contact.js';
import { policies } from './site/content.js';
import { icon, readStorage, writeStorage } from './site/utils.js';
import { brand, ctaLabel, appUrl } from './site/shared.js';
const icons = { ArrowUpRight, ArrowRight, ArrowLeft, Check, ChevronRight, Users, ClipboardList, ShieldCheck, Wrench, Truck, ChartNoAxesCombined, BriefcaseBusiness, ReceiptText, HardHat, UserCheck, Hammer, Contact, Info, Link, Download, ScanLine, Radio, FileCheck, Eye, Clock, Paperclip, Menu, X, Settings2, Pause, Play, Plus, Minus, CheckCheck, MapPin, Circle, Mail, ChevronDown, Building2, Layers3 };
const refreshIcons = () => createIcons({ icons, attrs: { 'stroke-width': 1.6 } });
const path = location.pathname.replace(/\/$/, '') || '/';
const nav = [['/platform','The platform'],['/how-it-works','How it works'],['/pricing','Pricing'],['/about','Our approach']];
const titles = { '/':'Construction operations, connected', '/platform':'Explore the platform', '/how-it-works':'A working day, connected', '/pricing':'Plan your investment', '/contact':'Plan a pilot', '/about':'Our approach', '/legal':'Trust & policies', '/sign-in':'Workspace access' };
const policy = path.startsWith('/legal/') ? policies.find(p => p.slug === path.split('/')[2]) : null;
document.title = `${policy?.title || titles[path] || 'Page not found'} — Site Killick`;
document.querySelector('meta[name="description"]').content = 'Explore Site Killick: construction operations software designed to connect crew attendance, safety records, tools and equipment. Interactive product preview.';
const pages = {'/':homePage,'/platform':platformPage,'/how-it-works':rolesPage,'/pricing':pricingPage,'/contact':contactPage,'/about':aboutPage,'/legal':()=>legalPage(),'/sign-in':()=>signInPage(appUrl)};
const page = pages[path] ? pages[path]() : path.startsWith('/legal/') ? legalPage(path.split('/')[2]) : notFound();
document.querySelector('#app').innerHTML = `<header class="site-header"><div class="header-inner">${brand()}<nav class="desktop-nav" aria-label="Main navigation">${nav.map(([url,label])=>`<a href="${url}" ${path===url?'aria-current="page"':''}>${label}</a>`).join('')}</nav><div class="header-actions">${appUrl?'<a class="sign-in" href="/sign-in">Sign in</a>':''}<a class="button primary header-demo" href="/contact">${ctaLabel} ${icon('arrow-up-right')}</a><button class="menu-toggle icon-button" aria-label="Open navigation" aria-expanded="false" aria-controls="mobile-nav">${icon('menu')}</button></div></div><nav id="mobile-nav" class="mobile-nav" aria-label="Mobile navigation" hidden>${nav.map(([url,label])=>`<a href="${url}" ${path===url?'aria-current="page"':''}>${label}${icon('arrow-right')}</a>`).join('')}<a href="/contact">Contact ${icon('arrow-right')}</a></nav></header><main id="main" tabindex="-1">${page}</main><footer class="site-footer"><div class="wrap footer-top"><div class="footer-brand">${brand()}<p>A steady hand.<br>A clearer working day.</p><span class="footer-location">${icon('map-pin')} Inspired by Atlantic Canada</span></div><div><h2>Explore</h2>${nav.map(([url,label])=>`<a href="${url}">${label}</a>`).join('')}</div><div><h2>Let’s get started</h2><a href="/contact">Plan a pilot</a><a href="/platform">Try the walkthrough</a><a href="/legal/security">Security & data</a><a href="/legal/hardware">Hardware compatibility</a></div><div class="footer-note"><span class="status-dot"></span> Product preview<p>Explore the proposed workflows. Availability and pilot scope are agreed before rollout.</p></div></div><div class="wrap footer-bottom"><span>© ${new Date().getFullYear()} Site Killick</span><div><a href="/legal/privacy">Privacy</a><a href="/legal/terms">Terms</a><a href="/legal/accessibility">Accessibility</a><button id="preferences-open">Preferences</button></div><span>Leave the site at the site.</span></div></footer><dialog id="preferences-dialog" aria-labelledby="preferences-title"><div class="dialog-heading"><h2 id="preferences-title">Your preferences</h2><button class="icon-button" id="preferences-close" aria-label="Close preferences">${icon('x')}</button></div><p>No analytics or advertising trackers. Optional storage can remember your budget configuration.</p><label class="option-row"><span>Remember my configuration</span><input id="preferences-storage" type="checkbox" ${readStorage('sk-consent',{}).preferences?'checked':''}></label><button id="preferences-save" class="button primary">Save preferences</button><p id="preferences-status" role="status"></p></dialog>`;
refreshIcons();
const menu = document.querySelector('.menu-toggle'), mobile = document.querySelector('#mobile-nav');
const closeMenu = () => { mobile.hidden=true;menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','Open navigation'); };
menu.onclick=()=>{const open=mobile.hidden;mobile.hidden=!open;menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'Close navigation':'Open navigation');};
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu();});
const dialog=document.querySelector('#preferences-dialog');
document.querySelector('#preferences-open').onclick=()=>dialog.showModal();
document.querySelector('#preferences-close').onclick=()=>dialog.close();
document.querySelector('#preferences-save').onclick=()=>{const preferences=document.querySelector('#preferences-storage').checked;const saved=writeStorage('sk-consent',{preferences});if(!preferences){try{localStorage.removeItem('sk-pricing');localStorage.removeItem('sk-motion');}catch{}}if(saved)dialog.close();else document.querySelector('#preferences-status').textContent='Storage is unavailable in this browser.';};
if(path==='/')bindHome(refreshIcons);
if(path==='/platform')bindPlatform(refreshIcons);
if(path==='/how-it-works')bindRoles(refreshIcons);
if(path==='/pricing')bindPricing();
if(path==='/contact')bindContact(refreshIcons);
